
services:
  nifi:
    image: apache/nifi:latest
    container_name: nifi
    restart: always
    ports:
      - "8080:8080"
      - "8443:8443" # Secure HTTPS port if needed
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_WEB_HTTPS_PORT=8443
      - NIFI_REGISTRY_URL=http://nifi-registry:18080
      - SINGLE_USER_CREDENTIALS_USERNAME=nifiuser 
      - SINGLE_USER_CREDENTIALS_PASSWORD=nifipassword123 
    volumes:
      - /home/dmboup/nifi_tuto/input:/opt/nifi/input/
      - /home/dmboup/nifi_tuto/output:/opt/nifi/output/
    networks:
      - nifi_network

  nifi-registry:
    image: apache/nifi-registry:latest
    container_name: nifi-registry
    restart: always
    ports:
      - "18080:18080"
    environment:
      - NIFI_REGISTRY_WEB_HTTP_PORT=18080
    volumes:
      - nifi_registry_data:/opt/nifi-registry/nifi-registry-current/data
    networks:
      - nifi_network

networks:
  nifi_network:
    driver: bridge

volumes:
  nifi_data:
  nifi_registry_data:
